# @package _global_

dataset_name: ps_female_3

dataset:
  name: people_snapshot
  root_dir: "../people_snapshot_public"
  subject: female-3-casual

  train_frames: [ 0, 1, 4 ]
  val_frames: [ 0, 1, 4 ]
  test_frames:
    pose: [0, 1, 4]
    all: [0, 1, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 540
    - 540

  resolution: -1
  white_background: false
  data_device: cuda
  eval: false

opt:
  densify_grad_threshold: 0.0001