# @package _global_

dataset_name: zju_313_mono

dataset:
  name: zjumocap
  root_dir: "../ZJUMoCap"
  subject: CoreView_313
  refine: false

  train_views: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '22', '23']
  val_views: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '22', '23']
  test_views:
    view: ${dataset.val_views}
    video: ['12']
    all: []
  predict_views: ['1']

  train_frames: [ 0, 1, 1 ]
  val_frames: [ 0, 1, 1 ]
  test_frames:
    view: [0, 1, 30]
    video: [0, 1, 1]
    all: [0, 1, 1]
  predict_frames: [0, 0, 1]

  reconstruct_views: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '22', '23']
  # means the first frame!
  reconstruct_frames: [0, 1, 1]

  img_hw:
    - 512
    - 512

  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false

  # per_face_TBN per_vertex_TBN
  rot_init: per_vertex_TBN