# @package _global_

texture_name: fusion_mlp

model:
  gaussian:
    use_sh: false
    feature_dim: 32
  texture:
    name: fusion_mlp

    feature_dim: ${model.gaussian.feature_dim}
    use_xyz: true
#    use_cov: false
#    use_normal: false
    sh_degree: 3
#    non_rigid_dim: 0
    latent_dim: 16

    cano_view_dir: true
    view_noise: 45
    use_ref: true
    use_dir_normal_dot: true
    # diffuse specular fusion
    texture_mode: fusion

    mlp:
      n_neurons: 64
      n_hidden_layers: 2
      skip_in: []
      cond_in: []
      multires: 0

    #TODO
    bottleneck_feature_dim: 256
    roughness_bias: 1.0
    ide:
      degree: 5

opt:
  feature_lr: 1e-3
  texture_lr: 1e-3
  tex_latent_lr: 1e-3
  latent_weight_decay: 0.05